<?php
/**
 * Merge tag rendering.
 *
 * @package Hiveclerk
 */

declare( strict_types=1 );

namespace Hiveclerk\Modules\Email\Services;

use Hiveclerk\Domain\Lead\Lead;

/**
 * Turns `{{first_name}}` into a name, and nothing else into anything.
 *
 * ## An unknown tag renders empty, never as itself
 *
 * A typo in a template must not put `{{fist_name}}` in front of a
 * customer's prospect. Leaving the literal in place is the behaviour most
 * template engines default to and it is exactly wrong here: the failure
 * is visible to the wrong person and it is visible as evidence that the
 * email was generated by software.
 *
 * ## Fallbacks are part of the tag, not an afterthought
 *
 * `{{first_name|there}}` renders "there" when the name is unknown, so
 * "Hi {{first_name|there}}," reads correctly either way. Without it,
 * every template either greets somebody by name or greets nobody, and a
 * lead captured from an address alone gets "Hi ,".
 *
 * Values are escaped at render time. A lead's company name came from a
 * website visitor typing into a chat window, and it lands in an HTML
 * email — this is the boundary where that stops being a problem.
 */
final class MergeTags {

	/**
	 * Tags a template may use, with what they render.
	 *
	 * Served to the builder so the editor's tag list and the renderer
	 * cannot drift apart.
	 *
	 * @var array<string, string>
	 */
	private const TAGS = array(
		'first_name'  => 'The lead’s first name',
		'last_name'   => 'The lead’s last name',
		'full_name'   => 'Both names, or the address if neither is known',
		'email'       => 'The lead’s email address',
		'company'     => 'The lead’s company',
		'job_title'   => 'The lead’s job title',
		'phone'       => 'The lead’s phone number',
		'site_name'   => 'This site’s name',
		'site_url'    => 'This site’s address',
		'unsubscribe' => 'The unsubscribe link',
	);

	/**
	 * Render a template against one lead.
	 *
	 * @param string      $template       Text with merge tags.
	 * @param Lead        $lead           Recipient.
	 * @param string|null $unsubscribeUrl Unsubscribe link, when there is one.
	 * @param bool        $escape         Whether values are HTML-escaped.
	 * @return string
	 */
	public function render( string $template, Lead $lead, ?string $unsubscribeUrl = null, bool $escape = true ): string {
		$values = $this->values( $lead, $unsubscribeUrl );

		$rendered = preg_replace_callback(
			'/\{\{\s*([a-z_]+)\s*(?:\|([^}]*))?\}\}/i',
			static function ( array $matches ) use ( $values, $escape ): string {
				$key      = strtolower( $matches[1] );
				$fallback = isset( $matches[2] ) ? trim( $matches[2] ) : '';

				if ( ! array_key_exists( $key, $values ) ) {
					return '';
				}

				$value = '' === $values[ $key ] ? $fallback : $values[ $key ];

				return $escape ? esc_html( $value ) : $value;
			},
			$template
		);

		return null === $rendered ? $template : $rendered;
	}

	/**
	 * The tags an editor may offer.
	 *
	 * @return array<int, array<string, string>>
	 */
	public function vocabulary(): array {
		$tags = array();

		foreach ( self::TAGS as $key => $description ) {
			$tags[] = array(
				'tag'         => '{{' . $key . '}}',
				'key'         => $key,
				'description' => $description,
			);
		}

		return $tags;
	}

	/**
	 * What each tag resolves to for one lead.
	 *
	 * @param Lead        $lead           Recipient.
	 * @param string|null $unsubscribeUrl Unsubscribe link.
	 * @return array<string, string>
	 */
	private function values( Lead $lead, ?string $unsubscribeUrl ): array {
		return array(
			'first_name'  => (string) $lead->firstName,
			'last_name'   => (string) $lead->lastName,
			'full_name'   => $lead->displayName(),
			'email'       => (string) $lead->email,
			'company'     => (string) $lead->company,
			'job_title'   => (string) $lead->jobTitle,
			'phone'       => (string) $lead->phone,
			'site_name'   => (string) get_bloginfo( 'name' ),
			'site_url'    => home_url(),
			'unsubscribe' => (string) $unsubscribeUrl,
		);
	}
}
