<?php
/**
 * Email automation tables.
 *
 * @package Hiveclerk
 */

declare( strict_types=1 );

namespace Hiveclerk\Database\Migrations;

use Hiveclerk\Database\Migration;
use Hiveclerk\Database\Schema;

/**
 * Creates the sequence, enrolment and send-log tables.
 */
final class M0005_Email extends Migration {

	public function version(): int {
		return 5;
	}

	public function description(): string {
		return 'Create email automation tables';
	}

	public function up(): void {
		$sequences    = Schema::table( Schema::EMAIL_SEQUENCES );
		$steps        = Schema::table( Schema::SEQUENCE_STEPS );
		$enrollments  = Schema::table( Schema::SEQUENCE_ENROLLMENTS );
		$log          = Schema::table( Schema::EMAIL_LOG );
		$suppressions = Schema::table( Schema::SUPPRESSIONS );
		$charset      = $this->charset();

		$this->run(
			"CREATE TABLE IF NOT EXISTS `{$sequences}` (
				id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				uuid            CHAR(36)        NOT NULL,
				name            VARCHAR(191)    NOT NULL,
				status          VARCHAR(20)     NOT NULL DEFAULT 'draft',
				trigger_type    VARCHAR(50)     NOT NULL,
				trigger_config  JSON                NULL,
				exit_conditions JSON                NULL,
				from_name       VARCHAR(191)        NULL,
				from_email      VARCHAR(191)        NULL,
				reply_to        VARCHAR(191)        NULL,
				enrolled_count  INT UNSIGNED    NOT NULL DEFAULT 0,
				created_at      DATETIME        NOT NULL,
				updated_at      DATETIME        NOT NULL,
				deleted_at      DATETIME            NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY uq_uuid (uuid),
				KEY idx_status_trigger (status, trigger_type)
			) ENGINE=InnoDB {$charset} ROW_FORMAT=DYNAMIC"
		);

		// approved_by is the human gate on AI-drafted copy. A sequence step
		// generated by a model does not send until a person signs it off.
		$this->run(
			"CREATE TABLE IF NOT EXISTS `{$steps}` (
				id             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				sequence_id    BIGINT UNSIGNED NOT NULL,
				position       SMALLINT        NOT NULL DEFAULT 0,
				delay_minutes  INT UNSIGNED    NOT NULL DEFAULT 0,
				subject        VARCHAR(500)    NOT NULL,
				body_html      LONGTEXT        NOT NULL,
				body_text      LONGTEXT            NULL,
				ai_generated   TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
				approved_by    BIGINT UNSIGNED     NULL,
				approved_at    DATETIME            NULL,
				conditions     JSON                NULL,
				created_at     DATETIME        NOT NULL,
				updated_at     DATETIME        NOT NULL,
				PRIMARY KEY  (id),
				KEY idx_sequence (sequence_id, position)
			) ENGINE=InnoDB {$charset} ROW_FORMAT=DYNAMIC"
		);

		$this->run(
			"CREATE TABLE IF NOT EXISTS `{$enrollments}` (
				id             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				sequence_id    BIGINT UNSIGNED NOT NULL,
				lead_id        BIGINT UNSIGNED NOT NULL,
				status         VARCHAR(20)     NOT NULL DEFAULT 'active',
				current_step   SMALLINT        NOT NULL DEFAULT 0,
				next_send_at   DATETIME            NULL,
				exit_reason    VARCHAR(100)        NULL,
				enrolled_at    DATETIME        NOT NULL,
				completed_at   DATETIME            NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY uq_sequence_lead (sequence_id, lead_id),
				KEY idx_due (status, next_send_at),
				KEY idx_lead (lead_id)
			) ENGINE=InnoDB {$charset}"
		);

		$this->run(
			"CREATE TABLE IF NOT EXISTS `{$log}` (
				id             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				enrollment_id  BIGINT UNSIGNED     NULL,
				step_id        BIGINT UNSIGNED     NULL,
				lead_id        BIGINT UNSIGNED NOT NULL,
				message_id     VARCHAR(191)        NULL,
				to_email       VARCHAR(191)    NOT NULL,
				subject        VARCHAR(500)    NOT NULL,
				status         VARCHAR(20)     NOT NULL DEFAULT 'queued',
				error          TEXT                NULL,
				sent_at        DATETIME            NULL,
				opened_at      DATETIME            NULL,
				clicked_at     DATETIME            NULL,
				created_at     DATETIME        NOT NULL,
				PRIMARY KEY  (id),
				KEY idx_enrollment (enrollment_id),
				KEY idx_lead (lead_id, created_at),
				KEY idx_status (status, created_at),
				KEY idx_message_id (message_id)
			) ENGINE=InnoDB {$charset} ROW_FORMAT=DYNAMIC"
		);

		// Survives lead erasure: honouring an unsubscribe is a legal basis for
		// retaining the hash after the rest of the record is gone.
		$this->run(
			"CREATE TABLE IF NOT EXISTS `{$suppressions}` (
				id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
				email_hash  CHAR(64)        NOT NULL,
				reason      VARCHAR(50)     NOT NULL,
				created_at  DATETIME        NOT NULL,
				PRIMARY KEY  (id),
				UNIQUE KEY uq_email_hash (email_hash)
			) ENGINE=InnoDB {$charset}"
		);
	}

	public function down(): void {
		$this->drop( Schema::SUPPRESSIONS );
		$this->drop( Schema::EMAIL_LOG );
		$this->drop( Schema::SEQUENCE_ENROLLMENTS );
		$this->drop( Schema::SEQUENCE_STEPS );
		$this->drop( Schema::EMAIL_SEQUENCES );
	}
}
