<?php
/**
 * SEC-04 route gating check.
 *
 * Asserts that every Hiveclerk REST route declares a permission callback
 * that actually decides something. A route registered without one, or with
 * __return_true, ships open — this is the check that stops that reaching
 * production.
 *
 * Run with:  wp eval-file tools/verify-routes.php
 *
 * Exits non-zero on failure so CI can gate on it.
 *
 * No declare(strict_types=1): wp eval-file evals this file's contents, and a
 * strict_types declaration is only legal as the first statement of a script.
 *
 * @package Hiveclerk
 */

/*
 * No do_action( 'rest_api_init' ) here on purpose.
 *
 * rest_get_server() fires it itself. Firing it first as well gave the
 * routes two registration passes, which is one more than a real request
 * gets — and that extra pass hid a bug where controllers added by the
 * hiveclerk/rest/register hook were only registered on the second run.
 * The checker reported every route present while the site returned 404.
 *
 * One pass, like production.
 */
$hvc_routes = rest_get_server()->get_routes();
$hvc_ours   = array_filter(
	array_keys( $hvc_routes ),
	static fn ( string $route ): bool => str_starts_with( $route, '/hiveclerk/v1' )
);

/*
 * The namespace index (/hiveclerk/v1 exactly) is generated by WordPress core
 * for every registered namespace, not by us. It lists route names and nothing
 * else, and core owns its permission model, so it is excluded here.
 */
$hvc_ours = array_filter(
	$hvc_ours,
	static fn ( string $route ): bool => '/hiveclerk/v1' !== $route
);

$hvc_failures = array();

foreach ( $hvc_ours as $hvc_route ) {
	foreach ( $hvc_routes[ $hvc_route ] as $hvc_handler ) {
		if ( ! isset( $hvc_handler['permission_callback'] ) ) {
			$hvc_failures[] = $hvc_route . ' — no permission_callback';
			continue;
		}

		$hvc_callback = $hvc_handler['permission_callback'];

		if ( '__return_true' === $hvc_callback ) {
			$hvc_failures[] = $hvc_route . ' — permission_callback is __return_true';
		}
	}
}

printf( "Checked %d Hiveclerk routes.\n", count( $hvc_ours ) );

foreach ( $hvc_ours as $hvc_route ) {
	printf( "  %s\n", $hvc_route );
}

if ( array() !== $hvc_failures ) {
	echo "\nSEC-04 FAILED:\n";

	foreach ( $hvc_failures as $hvc_failure ) {
		printf( "  %s\n", $hvc_failure );
	}

	exit( 1 );
}

echo "\nSEC-04 passed: every route is gated.\n";
